name: CI-CD for node app 
on:
 push:
  branches:
    - main 
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4 
        with:
          repository: khushi13131313/Blobstation_GitHub
        # sonarqube quality check quality check 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
         args: >
          -Dsonar.projectKey=Blobstation_GitHub
          -Dsonar.projectName=Blobstation_GitHub
          -Dsonar.sources=.
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}  
           
           
           # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
           # Build the Docker image
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/node-app-gitaction:latest .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/node-app-gitaction:latest

      # Deploy to EC2 using SSH/
      # - name: Deploy on EC2
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USER }}/node-app-gitaction:latest
      #       docker run -d -p 3000:3000 --name node-app-github ${{ secrets.DOCKER_USER }}/node-app-gitaction:latest
